name: Events Demo 1
on:
  pull_request:
    types:
      - opened
      - closed # Keown Added
    branches:
      - main
      - 24Mar # main
      #you can list other branches here
  workflow_dispatch:
  push:
    branches:
      - main # main
      - 24Mar 
      #you can list other branches here
      
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
