BEGIN TRAN
CREATE SEQUENCE newSeq AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CYCLE
CREATE SEQUENCE secondSeq AS INT
SELECT * FROM sys.sequences

BEGIN TRAN
CREATE SEQUENCE newSeq AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1
CACHE 50
CREATE SEQUENCE secondSeq AS INT
SELECT * FROM sys.sequences

