name: Deploy SQL Database
on:  workflow_dispatch
# pull_request:
#   type:
#     - closed
#   branches:
#     - main

jobs:
  deploy-dev:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add Microsoft repository for SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
      - name: Install SQL Server client
        run: sudo apt-get install -y mssql-tools unixodbc-dev
      - name: Add SQL Server tools to PATH
        run: echo "/opt/mssql-tools/bin" >> $GITHUB_PATH
      - name: Test Connection to SQL Server
        env:
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          sqlcmd -S "$DEV_SERVER" -U "$DEV_DB_USER" -P "$DEV_DB_PASSWORD" -Q "SELECT @@VERSION" || echo "Connection failed: check server, user, or password"
      - name: Create Database
        env:
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          sqlcmd -S "$DEV_SERVER" -U "$DEV_DB_USER" -P "$DEV_DB_PASSWORD" -d "master" -i "DatabaseAutomation/1_CreateDatabase.sql"
      - name: Create Table
        env:
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          sqlcmd -S "$DEV_SERVER" -U "$DEV_DB_USER" -P "$DEV_DB_PASSWORD" -d "master" -i "DatabaseAutomation/2_CreateTable.sql"
      - name: Create Stored Procedure
        env:        
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          sqlcmd -S "$DEV_SERVER" -U "$DEV_DB_USER" -P "$DEV_DB_PASSWORD" -d "master" -i  "DatabaseAutomation/3_StoredProcedure.sql"
      - name: Execute Stored Procedure
        env:
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          sqlcmd -S "$DEV_SERVER" -U "$DEV_DB_USER" -P "$DEV_DB_PASSWORD" -d "master" -i  "DatabaseAutomation/4_ExecuteStoredProcedure.sql"

  deploy-prod:
    needs: deploy-dev
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add Microsoft repository for SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
      - name: Install SQL Server client
        run: sudo apt-get install -y mssql-tools unixodbc-dev
      - name: Add SQL Server tools to PATH
        run: echo "/opt/mssql-tools/bin" >> $GITHUB_PATH
      - name: Test Connection to SQL Server
        env:
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          sqlcmd -S "$PROD_SERVER" -U "$PROD_DB_USER" -P "$PROD_DB_PASSWORD" -Q "SELECT @@VERSION" || echo "Connection failed: check server, user, or password"
      - name: Create Database
        env:
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          sqlcmd -S "$PROD_SERVER" -U "$PROD_DB_USER" -P "$PROD_DB_PASSWORD" -d "master" -i "DatabaseAutomation/1_CreateDatabase.sql"
      - name: Create Table
        env:
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          sqlcmd -S "$PROD_SERVER" -U "$PROD_DB_USER" -P "$PROD_DB_PASSWORD"  -i "DatabaseAutomation/2_CreateTable.sql"
      - name: Create Stored Procedure
        env:
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          sqlcmd -S "$PROD_SERVER" -U "$PROD_DB_USER" -P "$PROD_DB_PASSWORD"  -i "DatabaseAutomation/3_StoredProcedure.sql"
      - name: Execute Stored Procedure
        env:
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          sqlcmd -S "$PROD_SERVER" -U "$PROD_DB_USER" -P "$PROD_DB_PASSWORD"  -i "DatabaseAutomation/4_ExecuteStoredProcedure.sql"
