name: SQL Test with MySQL

on: [push, pull_request]

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL Server
        uses: jordiprats/mysql-action@1.1
        with:
          mysql version: '8.0'  # Set MySQL version (optional, default: latest)
          mysql root password: 'root'  # Root password
          test dir: 'DatabaseAdministration/SQLStatements'  # Directory containing SQL test scripts
          debug: 1  # Enable debugging (optional)

      - name: Run SQL Tests
        run: |
          sudo apt-get install -y mysql-client
          for file in sql_tests/*.sql; do
            echo "Running test: $file"
            mysql --user=root --password=root --host=127.0.0.1 < "$file" || exit 1
          done
