name: Install SSIS Package

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  install-ssis:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # This still needs PowerShell – can't convert this to cmd
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Create SSIS Catalog Folder (CMD)
        run: |
          sqlcmd -S "%SERVER%" -U %DB_USER% -P %DB_PASSWORD% -d SSISDB -Q "IF NOT EXISTS (SELECT 1 FROM [SSISDB].[catalog].[folders] WHERE name = N'Timesheet') EXEC [SSISDB].[catalog].[create_folder] @folder_name = N'Timesheet'" -b -m 1 -r 1 -t 30
        shell: cmd
        env:
          SERVER: ${{ secrets.SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        working-directory: ${{ github.workspace }}

      - name: Deploy SSIS Package (CMD)
        run: |
          SSISDeploy -s HandsOnProjects/Timesheet/SSIS/TimeSheet_Project/ImportingV8Editing.dtsx -d "catalog;/SSISDB/Timesheet/TimeSheet_Project" -cs "Server=%SERVER%;User ID=%DB_USER%;Password=%DB_PASSWORD%;" -v
        shell: cmd
        env:
          SERVER: ${{ secrets.SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        working-directory: ${{ github.workspace }}
