name: Install SSIS Package

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  install-ssis:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Create SSIS Catalog Folder
        shell: cmd
        run: |
          sqlcmd -S "SAMBE2025006" -E -d SSISDB -Q "IF NOT EXISTS (SELECT 1 FROM [SSISDB].[catalog].[folders] WHERE name = N'Timesheet') EXEC [SSISDB].[catalog].[create_folder] @folder_name = N'Timesheet'" -b -m 1 -r 1 -t 30
        working-directory: ${{ github.workspace }}

      - name: Deploy SSIS Package
        shell: cmd
        run: |
          SSISDeploy -s HandsOnProjects\Timesheet\SSIS\TimeSheet_Project/ImportingV8Editing.dtsx -d "catalog;/SSISDB/Timesheet/TimeSheet_Project" -cs "Server=SAMBE2025006;Integrated Security=SSPI;" -at:win -v
        working-directory: ${{ github.workspace }}
