name: Install SSIS Package

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  install-ssis:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Verify SSISDeploy is accessible
        shell: cmd
        run: |
          where SSISDeploy
          if %ERRORLEVEL% neq 0 (
            echo SSISDeploy not found in PATH. Ensure it is installed and added to PATH.
            exit /b 1
          )
        working-directory: ${{ github.workspace }}

      - name: Create SSIS Catalog Folder
        shell: cmd
        run: |
          sqlcmd -S "%SERVER%" -U %DB_USER% -P "%DB_PASSWORD%" -d SSISDB -Q "IF NOT EXISTS (SELECT 1 FROM [SSISDB].[catalog].[folders] WHERE name = N'Timesheet') EXEC [SSISDB].[catalog].[create_folder] @folder_name = N'Timesheet'" -b -m 1 -r 1 -t 30
        working-directory: ${{ github.workspace }}
        env:
          SERVER: ${{ secrets.SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Deploy SSIS Package
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\SSIS\SSISDeploy.exe" -s HandsOnProjects\Timesheet\SSIS\TimeSheet_Project\ImportingV8Editing.dtsx -d "catalog;/SSISDB/Timesheet/TimeSheet_Project" -cs "Server=%SERVER%;User ID=%DB_USER%;Password=%DB_PASSWORD%;" -v
        working-directory: ${{ github.workspace }}
        env:
          SERVER: ${{ secrets.SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
