name: Deploy SQL Server Database, SSIS Packages, and Agent Job

on:
  workflow_dispatch:

jobs:
  Deploy-DB:
    runs-on: windows-latest # Required for SSIS tools
    environment: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy database and table scripts
      - name: Deploy Database and Tables
        run: |
          sqlcmd -S "${{ secrets.SERVER }}" -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d master -i HandsOnProjects/Timesheet/SQL/CreateDatabase.sql
          sqlcmd -S "${{ secrets.SERVER }}" -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d TimesheetDB -i HandsOnProjects/Timesheet/SQL/CreateAllTablesSP.sql
        working-directory: ${{ github.workspace }}

