name: Deploy SQL Server Database, SSIS Packages, and Agent Job

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest # Required for SSIS tools
    environment: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install SQL Server SSIS DevOps Tools
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Debug: Verify SSIS package file exists
      - name: Verify SSIS Package File
        run: dir HandsOnProjects\Timesheet\SSIS\TimeSheet_Project
        working-directory: ${{ github.workspace }}

      # Deploy database and table scripts
      - name: Deploy Database and Tables
        run: |
          sqlcmd -S "${{ secrets.SERVER }}" -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d master -i HandsOnProjects/Timesheet/SQL/CreateDatabase.sql
          sqlcmd -S "${{ secrets.SERVER }}" -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d TimesheetDB -i HandsOnProjects/Timesheet/SQL/CreateAllTablesSP.sql
        working-directory: ${{ github.workspace }}

      # Deploy SSIS package to SSIS Catalog
      - name: Deploy SSIS Package
        shell: pwsh
        run: |
          SSISDeploy.exe -s:"HandsOnProjects/Timesheet/SSIS/TimeSheet_Project/ClientAndEmployeeExtraction.dtsx" -d:"catalog;/SSISDB/Timesheet/MyProject;${{ secrets.SERVER }}" -a:SQL -u:${{ secrets.DB_USER }} -p:${{ secrets.DB_PASSWORD }}
        working-directory: ${{ github.workspace }}

      # Create and configure SQL Server Agent Job
      - name: Create SQL Server Agent Job
        run: |
          sqlcmd -S "${{ secrets.SERVER }}" -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d msdb -i HandsOnProjects/Timesheet/SQL/JobSchedule.sql
        working-directory: ${{ github.workspace }}
