name: Deploy SQL Server Database, SSIS Packages, and Agent Job

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest # Required for SSIS tools
    environment: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install SQL Server SSIS DevOps Tools
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Deploy database and table scripts
      - name: Deploy Database and Tables
        run: |
          sqlcmd -S ${{ secrets.SERVER }} -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d master -i Hands-on Projects/Timesheet/SQL/CreateDatabase.sql
          sqlcmd -S ${{ secrets.SERVER }} -U ${{  secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d TimesheetDB -i Hands-on Projects/Timesheet/SQL/CreateAllTablesSP.sql
        working-directory: ${{ github.workspace }}
